#pragma once

#ifdef STITCHESAPI_EXPORTS
#include <winioctl.h>
#endif

#define KERNELDEVICE_DEVICE_NAME        L"Stitches"
#define KERNELDEVICE_DEVICE_FILE        L"\\\\.\\" KERNELDEVICE_DEVICE_NAME
#define FILE_DEVICE_KERNELCODE			0x8005

#define DEVICE_NAME			L"\\Device\\" KERNELDEVICE_DEVICE_NAME
#define SYMBOLICLINK_NAME	L"\\DosDevices\\" KERNELDEVICE_DEVICE_NAME

constexpr ULONG IOCTL_STITCHES_ADD_TRUST_PROCESS = static_cast<ULONG>(CTL_CODE(FILE_DEVICE_KERNELCODE, 0x800, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS));